apiVersion: v1
kind: ConfigMap
metadata:
  name: kita
data:
  application.yml: |
    kita:
      issuers:
        letsencrypt-staging:
          directory-url: https://acme-staging-v02.api.letsencrypt.org/directory
          emails:
            - CONFIGURE_EMAIL
          terms-of-service-agreed: SET_TO_TRUE
        letsencrypt-prod:
          directory-url: https://acme-v02.api.letsencrypt.org/directory
          emails:
            - CONFIGURE_EMAIL
          terms-of-service-agreed: SET_TO_TRUE