---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kita
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kita
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - networking.k8s.io/v1
    resources:
      - ingresses
    verbs:
      - create
      - list
      - watch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kita
subjects:
  - kind: ServiceAccount
    name: kita
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kita
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kita
  labels:
    app: kita
spec:
  replicas: 1
  template:
    metadata:
      name: kita
      labels:
        app: kita
    spec:
      serviceAccountName: kita
      containers:
        - name: app
          image: ghcr.io/itzg/kita
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /application/config
              name: configs
      volumes:
        - name: configs
          configMap:
            name: kita
  selector:
    matchLabels:
      app: kita
---
apiVersion: v1
kind: Service
metadata:
  name: kita
  labels:
    app: kita
    acme.itzg.github.io/role: solver
spec:
  selector:
    app: kita
  ports:
    - port: 8080
      name: http
  type: NodePort