apiVersion: apps/v1
kind: Deployment
metadata:
  name: kita-dev
  labels:
    app: kita-dev
spec:
  replicas: 1
  template:
    metadata:
      name: kita-dev
      labels:
        app: kita-dev
    spec:
      serviceAccountName: kita-dev
      containers:
        - name: app
          image: kita-dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: LOGGING_LEVEL_APP
              value: DEBUG
            - name: KITA_SOLVER_ROLE
              value: solver-dev
          volumeMounts:
            - mountPath: /application/config
              name: configs
      imagePullSecrets:
        - name: ghcr-pull
      volumes:
        - name: configs
          configMap:
            # Must be created manually on the target cluster
            # with an application.properties or application.yml entry
            name: kita-dev
  selector:
    matchLabels:
      app: kita-dev
