apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingress-tls-acme-dev
rules:
  - apiGroups: [""]
    resources: ["secrets", "services"]
    verbs: ["get"]
  - apiGroups:
      - networking.k8s.io/v1
    resources:
      - ingresses
    verbs:
      - list
      - watch
      - create
      - delete
