apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kita-dev
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - networking.k8s.io/v1
    resources:
      - ingresses
    verbs:
      - create
      - list
      - watch
      - delete
