apiVersion: v1
kind: Service
metadata:
  name: ingress-tls-acme-dev
  labels:
    app: ingress-tls-acme-dev
    acme.itzg.github.io/role: solver
spec:
  selector:
    app: ingress-tls-acme-dev
  ports:
    - port: 8080
      name: http
  type: NodePort