apiVersion: v1
kind: Service
metadata:
  name: kita-dev
  labels:
    app: kita-dev
    acme.itzg.github.io/role: solver-dev
spec:
  selector:
    app: kita-dev
  ports:
    - port: 8080
      name: http
  type: NodePort