name: Build

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  build:
    uses: itzg/github-workflows/.github/workflows/simple-boot-image-to-ghcr.yml@main
    with:
      image-repo: "ghcr.io/itzg"
      image-platforms: "linux/amd64"
      java-version: "21"
      extra-gradle-tasks: test