name: PRs

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: itzg/github-workflows/.github/workflows/gradle-build.yml@main
    with:
      arguments: test
      include-test-report: true
      java-version: "18"
